name: exopets
description: An Ecommerce for Exotic Pets

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.7.1
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  file_picker: ^5.3.0
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.1
  flutter:
    sdk: flutter
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: ^4.6.5
  lottie: ^2.3.2
  shared_preferences: ^2.1.1
  webview_flutter: ^4.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/html/
    - assets/images/
    - assets/html/privacy_policy_files/
    - assets/html/term_and_condition_files/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
